# Generated by Django 4.0.2 on 2022-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
