# Generated by Django 4.0.2 on 2022-03-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_profile_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
    ]
